import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CalendarDays, Heart, Menu, MessageCircle, Scissors, Sparkles, Star, X } from 'lucide-react';
import './styles.css';
import { services, addOns, businessRules, calculateBookingTotal, buildBookingMessage } from './data/services.js';

const img = p => `/assets/images/${p}`;
const gallery = [
  { src: img('hero-1.jpg'), title: 'Soft glam finish', tag: 'Featured' },
  { src: img('braids-1.jpg'), title: 'Detailed braid work', tag: 'Braids' },
  { src: img('style-1.jpg'), title: 'Polished styling', tag: 'Styling' },
  { src: img('client-1.jpg'), title: 'Client-ready look', tag: 'Finish' },
  { src: img('braids-2.jpg'), title: 'Clean parts', tag: 'Braids' },
  { src: img('hero-2.jpg'), title: 'Salon-ready beauty', tag: 'Signature' },
  { src: img('IMG_3482.jpeg'), title: 'Protective style', tag: 'Detail' }
];
const reviews = [
  { name:'Client Review', text:'Professional, neat, and the finished style looked exactly how I wanted.', rating:5 },
  { name:'Approved Review', text:'Clean parts, smooth finish, and a comfortable appointment experience.', rating:5 },
  { name:'Returning Client', text:'Shawna takes her time and makes the style look polished every time.', rating:5 }
];
function Header({ page, setPage }) { const [open,setOpen]=useState(false); const nav=['Home','Gallery','Services','About','Booking','Reviews','Contact','Policies']; return <header className="site-header"><a className="brand" onClick={()=>setPage('Home')}><span>RB</span><div><strong>Ravishing Beauté</strong><small>Hair artistry by Shawna</small></div></a><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(n=><button key={n} className={page===n?'active':''} onClick={()=>{setPage(n);setOpen(false)}}>{n}</button>)}</nav></header> }
function Footer({ setPage }) { return <footer><div><h2>Ravishing Beauté</h2><p>Premium, appointment-based hair styling with clean parts, polished finishes, and a client-first booking experience.</p></div><div><strong>Hours</strong><p>{businessRules.hours}<br/>Closed Sunday and Monday</p></div><div><strong>Booking</strong><p>{businessRules.depositLabel}<br/>{businessRules.sameDay}</p><button onClick={()=>setPage('Booking')}>Request Appointment</button></div></footer> }
function Home({setPage}) { return <><section className="hero"><div className="hero-copy"><p className="eyebrow">Premium hair styling</p><h1>Polished styles, clean details, and a beauty experience that feels intentional.</h1><p>At Ravishing Beauté, we focus on neat parts, balanced styling, and client-ready finishes for braids, ponytails, quick weaves, and more.</p><div className="actions"><button onClick={()=>setPage('Booking')}>Book Now</button><button className="ghost" onClick={()=>setPage('Gallery')}>View Work</button></div></div><div className="hero-images"><img className="large" src={img('hero-1.jpg')}/><img src={img('braids-1.jpg')}/><img src={img('style-1.jpg')}/></div></section><section className="strip"><Card icon={<Scissors/>} title="Clean styling" text="Detailed parting and polished results."/><Card icon={<CalendarDays/>} title="By appointment" text="8:30 AM to 6:00 PM, Tuesday through Saturday."/><Card icon={<Sparkles/>} title="Clear pricing" text="Deposit and service details are shown before booking."/></section><Section title="Featured services" sub="A quick look at core Ravishing Beauté services."><div className="cards">{services.slice(0,4).map(s=><ServiceCard key={s.id} service={s}/>)}</div></Section><Section title="Client words" sub="Public reviews stay curated and approved before appearing."><div className="reviews">{reviews.slice(0,2).map((r,i)=><Review key={i} {...r}/>)}</div><button className="center" onClick={()=>setPage('Reviews')}>See All Reviews</button></Section></> }
function Gallery(){return <Section title="Gallery" sub="An editorial view of Ravishing Beauté styles and detail work."><div className="gallery">{gallery.map((g,i)=><figure className={i===0?'feature':''} key={g.src}><img src={g.src}/><figcaption><span>{g.tag}</span><strong>{g.title}</strong></figcaption></figure>)}</div></Section>}
function Services(){const cats=[...new Set(services.map(s=>s.category))];return <><Section title="Services / Pricing" sub="A clean salon menu with transparent booking rules.">{cats.map(cat=><div className="menu-group" key={cat}><h3>{cat}</h3><div className="cards">{services.filter(s=>s.category===cat).map(s=><ServiceCard key={s.id} service={s}/>)}</div></div>)}<div className="notice"><b>Hair included note:</b> {businessRules.includedHairNote}</div><div className="notice"><b>Deposit:</b> {businessRules.depositLabel}. Remaining balance is due at appointment.</div></Section></>}
function About(){return <section className="about"><img src={img('client-1.jpg')}/><div><p className="eyebrow">About your stylist</p><h1>Hi, I’m Shawna.</h1><p>I’ve been styling since 2016, starting by practicing on friends and family and growing into a more polished, consistent approach over time. My experience includes braids, ponytails, quick weaves, and everyday styles that still feel elevated.</p><p>I graduated cosmetology school in 2023, and my focus now is simple: improve consistency, keep parts clean, and deliver finished looks that feel neat, confident, and Ravishing Beauté ready.</p></div></section>}
function Booking(){const [form,setForm]=useState({serviceId:'knotless-md',addOnIds:[]}); const quote=useMemo(()=>calculateBookingTotal(form.serviceId,form.addOnIds),[form]); const toggle=id=>setForm(f=>({...f,addOnIds:f.addOnIds?.includes(id)?f.addOnIds.filter(x=>x!==id):[...(f.addOnIds||[]),id]})); const send=()=>{const msg=encodeURIComponent(buildBookingMessage(form)); window.location.href=`sms:?&body=${msg}`}; return <Section title="Booking Request" sub="Choose a service, review the estimated price, then send a prefilled request by text."><div className="booking-grid"><div className="form-card"><label>Name<input onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Phone<input onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Service<select value={form.serviceId} onChange={e=>setForm({...form,serviceId:e.target.value})}>{services.map(s=><option value={s.id} key={s.id}>{s.name} - ${s.price}</option>)}</select></label><div><label>Add-ons</label><div className="checks">{addOns.map(a=><button type="button" className={form.addOnIds?.includes(a.id)?'picked':''} onClick={()=>toggle(a.id)} key={a.id}>{a.name} +${a.price}</button>)}</div></div><label>Preferred date<input type="date" onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Preferred time<input type="time" onChange={e=>setForm({...form,time:e.target.value})}/></label><label>Notes<textarea onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Length, color, inspiration, questions..."/></label><button onClick={send}><MessageCircle/> Send Booking Text</button></div><aside className="quote"><h3>Estimated booking</h3><p>{quote.service.name}</p><dl><div><dt>Service</dt><dd>${quote.service.price}</dd></div><div><dt>Add-ons</dt><dd>${quote.addOnTotal}</dd></div><div><dt>Estimated total</dt><dd>${quote.estimatedTotal}</dd></div><div><dt>Deposit</dt><dd>${quote.depositDue}</dd></div><div><dt>Remaining balance</dt><dd>${quote.remainingBalance}</dd></div></dl><p className="small">{businessRules.includedHairNote}</p><p className="small">{businessRules.sameDay}</p></aside></div></Section>}
function Reviews(){return <Section title="Reviews" sub="Approved client feedback presented cleanly for trust."><div className="reviews">{reviews.map((r,i)=><Review key={i} {...r}/>)}</div><div className="notice">Review submissions should be admin-approved before appearing publicly.</div></Section>}
function Contact(){const [v,setV]=useState({}); const send=()=>{const body=encodeURIComponent(`Hi Ravishing Beauté, I have a question.\n\nName: ${v.name||''}\nQuestion: ${v.question||''}`); window.location.href=`sms:?&body=${body}`}; return <Section title="Contact" sub="Have a question before booking? Send it directly from your phone."><div className="form-card narrow"><label>Name<input onChange={e=>setV({...v,name:e.target.value})}/></label><label>Question<textarea onChange={e=>setV({...v,question:e.target.value})}/></label><button onClick={send}>Send Question</button></div></Section>}
function Policies(){return <Section title="Policies" sub="Clear expectations help every appointment stay smooth."><div className="policy-list">{['$25 deposit required to request an appointment.','Business hours are 8:30 AM to 6:00 PM by appointment.','Closed Sunday and Monday.','Same-day bookings are only available if approved.','Please come detangled to stay on schedule.','Braiding hair is included only in natural colors 1, 1B, 2, and 4 unless otherwise specified.','Late arrivals may affect the final style or appointment availability.'].map(x=><div><Heart/><p>{x}</p></div>)}</div></Section>}
function Card({icon,title,text}){return <div className="info-card">{icon}<h3>{title}</h3><p>{text}</p></div>}
function ServiceCard({service}){return <article className="service-card"><span>{service.category}</span><h3>{service.name}</h3><p>{service.details}</p><div><strong>${service.price}</strong><small>{service.duration}</small></div></article>}
function Review({name,text,rating}){return <article className="review"><div>{Array.from({length:rating}).map((_,i)=><Star key={i} size={16} fill="currentColor"/>)}</div><p>“{text}”</p><strong>{name}</strong></article>}
function Section({title,sub,children}){return <section className="section"><p className="eyebrow">Ravishing Beauté</p><h1>{title}</h1><p className="sub">{sub}</p>{children}</section>}
function App(){const [page,setPage]=useState('Home'); const pages={Home:<Home setPage={setPage}/>,Gallery:<Gallery/>,Services:<Services/>,About:<About/>,Booking:<Booking/>,Reviews:<Reviews/>,Contact:<Contact/>,Policies:<Policies/>}; return <><Header page={page} setPage={setPage}/><main>{pages[page]}</main><Footer setPage={setPage}/></>}
createRoot(document.getElementById('root')).render(<App/>);
